### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Svenare** [archshift/adusk#4]
Found YAML file at `/usr/share/adusk//cfg/keyboard-layout.yaml`
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/lib/python3.5/site-packages/adusk/controller.py", line 116, in input_thread
    sc = SteamController(callback=update, callback_args=(manager,))
  File "/usr/lib/python3.5/site-packages/steamcontroller/__init__.py", line 146, in **init**
    self._handle.claimInterface(number)
  File "/usr/lib/python3.5/site-packages/usb1.py", line 1141, in claimInterface
    mayRaiseUSBError(result)
  File "/usr/lib/python3.5/site-packages/usb1.py", line 107, in mayRaiseUSBError
    raiseUSBError(value)
  File "/usr/lib/python3.5/site-packages/usb1.py", line 103, in raiseUSBError
    raise STATUS_TO_EXCEPTION_DICT.get(value, USBError)(value)
usb1.USBErrorBusy: LIBUSB_ERROR_BUSY [-6]

Found font file at `/usr/share/adusk//fonts/DejaVuSansCondensed-Bold.ttf`
Traceback (most recent call last):
  File "/usr/bin/adusk", line 5, in <module>
    adusk.main()
  File "/usr/lib/python3.5/site-packages/adusk/adusk.py", line 39, in main
    scr = screen.Screen()
  File "/usr/lib/python3.5/site-packages/adusk/screen.py", line 53, in **init**
    self.font_manager = sdl2.ext.FontManager(font_path)
  File "/usr/lib/python3.5/site-packages/sdl2/ext/font.py", line 188, in **init**
    "FontManager requires sdlttf support")
sdl2.ext.compat.UnsupportedError: 'FontManager requires sdlttf support'
Exception ignored in: <bound method FontManager.__del__ of <sdl2.ext.font.FontManager object at 0x7f6e4c563d68>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sdl2/ext/font.py", line 202, in **del**
    self.close()
  File "/usr/lib/python3.5/site-packages/sdl2/ext/font.py", line 206, in close
    for alias, fonts in self.fonts.items():
AttributeError: 'FontManager' object has no attribute 'fonts'

**Comment by archshift** [comment]
Check out the dependencies in the README - I just updated them because you also need to have SDL_ttf and SDL_gfx.
